# apiVersion: v1
# kind: Pod
# metadata:
#   name: math-pod
# spec:
#   containers:
#   - name: math-add
#     image: ubuntu
#     command: ["expor", 3, "+", 2]
#   restartPolicy: Never

apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  template:
    spec:
      completions: 3
      parallelism: 3
      containers:
      - name: math-add
        image: ubuntu
        command: ["expr", "3", "+", "2"]
      restartPolicy: Never