apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: date-processor
    image: data-processor
  nodeSelector:
    size: Large
    //label에 Large가 있어야 됨
    //kubectl label nodes <node-name> <label-key>=<label-value>
    //kubectl label nodes node-1 size=Large